// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcrtrqublbczdcwhmejj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjcnRycXVibGJjemRjd2htZWpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MjU0NjAsImV4cCI6MjA2NjEwMTQ2MH0.E2MQeFjKVuG3D1FdcvNfLa72GRVzFqJs37ZLppm9i7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);